services:
  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_LOCAL_MACHINE_PORT:-55432}:5432"
    volumes:
      - prototype-db-data:/var/lib/postgresql/data
      - ${MEDIA_LOCATION:-./data/media/}processing:/data/media/processing
      - ${MEDIA_LOCATION:-./data/media/}downloadCache:/data/media/downloadCache
volumes:
  prototype-db-data:
